// ---------------------------------------------------------------------------
// 굿스플로 API 관련 상수
// ---------------------------------------------------------------------------

export const GF_API_BASE = 'https://api.goodsflow.io';
export const GF_TEST_API_BASE = 'https://test-api.goodsflow.io';

// 굿스플로 전용 택배사 코드 매핑 (굿스플로 API에서만 사용)
export const GF_TRANSPORTERS: Record<string, string> = {
  KOREX: 'CJ대한통운',
  EPOST: '우체국택배',
  HANJIN: '한진택배',
  LOTTE: '롯데택배',
  LOGEN: '로젠택배',
  ILYANG: '일양로지스',
  HOMEPICK: '홈픽택배',
  CVSNET: '편의점택배',
  EMS: 'EMS',
  BGF: 'BGF포스트',
  KOREXG: 'CJ대한통운국제특송',
  HANDEX: '한덱스',
  PANTOS: 'LX판토스',
  UPS: 'UPS',
  FEDEX: 'FedEx',
  KDEXP: '경동택배',
  HDEXP: '합동택배',
  CHUNIL: '천일택배',
  DAESIN: '대신택배',
  HPL: '한의사랑택배',
  KUNYOUNG: '건영택배',
  HONAM: '호남택배',
  SLX: 'SLX',
  YONGMA: '용마로지스',
  SEBANG: '세방택배',
  WONDERS: '원더스퀵',
  NHLOGIS: '농협택배',
  HILOGIS: 'HI택배',
  LOTTEGLOBAL: '롯데글로벌',
  DHL: 'DHL',
  TNT: 'TNT',
  USPS: 'USPS',
  IPARCEL: 'i-parcel',
  GSMNTON: 'GSM NtoN',
  SWGEXP: '성원글로벌',
  ACIEXPRESS: 'ACI Express',
  DAEWOON: '대운글로벌',
  AIRBOY: '에어보이익스프레스',
  KGLNET: 'KGL네트웍스',
  LINEEXP: 'LineExpress',
  TWOFASTEXP: '2FastExpress',
  GSIEXPRESS: 'GSI익스프레스',
  GTSLOGIS: 'GTS로지스',
  ECMSEXPRESS: 'ECMS익스프레스',
  EFS: 'EFS',
  DHLGLOBALMAIL: 'DHL GlobalMail',
  GPSLOGIX: 'GPS로직스',
  CRLX: '시알로지텍',
  BRIDGE: '브릿지로지스',
  HOMEINNOV: '홈이노베이션로지스',
  CWAY: 'cway express',
  GNETWORK: '자이언트',
  ACEEXP: 'ACE Express',
  WEVILL: '우리동네택배',
  FOREVERPS: '퍼레버택배',
  WARPEX: '워펙스',
  QXPRESS: '트랙스로지스',
  SMARTLOGIS: '스마트로지스',
  ESTHER: '에스더쉬핑',
  INTRAS: '로토스',
  EUNHA: '은하쉬핑',
  UFREIGHT: '유프레이트 코리아',
  LSERVICE: '엘서비스',
  TPMLOGIS: '로지스밸리택배',
  ZENIELSYSTEM: '제니엘시스템',
  ANYTRACK: '애니트랙',
  JLOGIST: '제이로지스트',
  CHAINLOGIS: '두발히어로',
  QRUN: '큐런',
  FRESHSOLUTIONS: '컬리넥스트마일',
  HIVECITY: '하이브시티',
  HANSSEM: '한샘',
  GOODSTOLUCK: '굿투럭',
  GENIEGO: '지니고',
  TODAYPICKUP: '오늘의픽업',
  NOGOK: '노곡물류',
  SPASYS1: '스페이시스원',
  LTL: 'LTL',
  LOGISPOT: '로지스팟',
  FRESHMATES: '프레시메이트',
  VROONG: '부릉',
  NKLS: 'NK로지솔루션',
  DODOFLEX: '만나플렉스',
  SHIPNERGY: '쉽너지',
  ETOMARS: '이투마스',
  VENDORPIA: '벤더피아',
  COSHIP: '캐나다쉬핑',
  GDAKOREA: '지디에이코리아',
  BABABA: '바바바로지스',
  TEAMFRESH: '팀프레시',
  ALLTAKOREA: '올타코리아',
  LOTTECHILSUNG: '롯데칠성',
  YUNDA: 'yunda express',
  VALEX: '발렉스',
  KOKUSAI: '국제익스플레스',
  XINPATEK: '윈핸드해운항공',
  HEREWEGO: '탱고앤고',
  WOONGJI: '웅지익스프레스',
  SBGLS: 'sbgls',
  PINGPONG: '핑퐁',
  YDH: 'YDH',
  CARGOPLEASE: '화물을부탁해',
  HOME1004: '1004홈',
  NAEUN: '나은물류',
  ACCCARGO: 'acccargo',
  NTLPS: '엔티엘피스',
  EKDP: '삼다수가정배송',
  HOTSINCARGO: '허싱카고코리아',
  SINOEX: 'SINOTRANS EXPRESS',
  DRABBIT: '딜리래빗',
  HOMEPICKTODAY: '홈픽오늘도착',
  DAERIM: '대림통운',
  LOGISPARTNER: 'UFO로지스',
  GOBOX: '고박스',
  FASTBOX: '패스트박스',
  PANSTAR: '팬스타국제특송',
  ACTCORE: '에이씨티앤코아물류',
  KJT: '케이제이티',
  THEBAO: '더바오',
  RUSH: '오늘회러쉬',
  KT: 'kt express',
  IBP: 'ibpcorp',
  HY: '한국야구르트',
  LOGISVALLEY: '로지스밸리',
  TODAY: '투데이',
  ONEDAYLOGIS: '라스트마일시스템즈',
  HKHOLDINGS: '에이치케이홀딩스',
  JIKGUMOON: '직구문',
  CUBEFLOW: '큐브플로우',
  SHFLY: '성훈물류',
  GBS: '지비에스',
  BANPOOM: '반품구조대',
  GLOVIS: '현대글로비스',
  ARGO: '아르고',
  MTINTER: '엠티인터네셔널',
  GDSP: '골드스넵스',
  WINION: '위니온로지스',
  YJSGLOBAL: 'YJS글로벌',
  SAGAWA: '사가와',
  YAMATO: '야마토',
  JPOST: '일본우편',
  INTERLOGIS: '인터로지스',
  WOOJIN: '우진글로벌로지스틱스',
  GHSPEED: '지에이치스피드',
  HOWSER: '하우저',
  WIDETECH: '와이드테크',
  ECOHAI: '에코하이',
  TONAMI: '토나미',
  DAIICHI: '제1화물',
  JMNP: '중앙일보엠앤피',
  FUKUYAMA: '후쿠야마통운',
  KURLYNEXTMILE: '컬리넥스트마일',
  ARAMEX: 'ARAMEX',
  BISNZ: 'BISNZ',
  INNOS: '이노스',
  SEORIM: '서림물류',
  WEMOVE: '위무브',
  POOLATHOME: '풀앳홈',
  SPARKLE: '스파클',
  ICS: 'ICS',
  HANMI: '한미포스트',
  HWATONG: '화통',
  ESTLA: '이스트라',
  IK: 'IK물류',
  PULMUONEWATER: '풀무원샘물',
  TSG: '티에스지로지스',
  OCS: 'ocs',
  MDLOGIS: '모든로지스',
  GCS: '지씨에스',
  FTF: '물류대장(LCS)',
  WOORIHB: '우리한방택배',
  JWTNL: 'JWTNL',
  LETUS: '레터스',
  JCLS: 'JCLS',
  GKGLOBAL: '지케이글로벌',
  GONELO: '고넬로',
  CASA: '신세계까사',
  BRCH: '비알씨에이치',
  HIDE: 'W7(리핑무역)',
  MORNINGGLOBAL: '모닝글로벌',
  ONTRAC: 'OnTrac',
  HERMES: 'Hermes',
  RETURNALL: '리터놀',
  EMART24: '이마트24',
  SEVENELEVEN: '세븐일레븐',
};

// 배송 상태 코드
export const GF_DELIVERY_STATUS: Record<string, string> = {
  PRINTED:     '송장 출력 완료',
  TRANSFERRED: '택배사 전송 완료',
  PICKUP:      '픽업 완료',
  IN_TRANSIT:  '이동 중',
  DLV_START:   '배송 출발',
  DLV_FAILED:  '배송 실패 (부재)',
  COMPLETED:   '배송 완료',
  RETURNED:    '반송 완료',
  CANCELED:    '취소',
  ERROR:       '오류',
};

// 굿스플로 배송 상태 → Freecart 주문 상태 매핑 (전이 대상만)
export const GF_STATUS_TO_ORDER_STATUS: Partial<Record<string, string>> = {
  COMPLETED: 'delivered',
  CANCELED:  'cancelled',
};

// 취소 사유 코드
export const GF_CANCEL_REASONS = [
  { code: 'NOT_SEND',      label: '미발송' },
  { code: 'RE_RECEIVED',   label: '취소 후 재신청' },
  { code: 'OTHER_SERVICE', label: '다른 배송사 이용' },
  { code: 'PICKUP_DELAY',  label: '집화 지연' },
  { code: 'ETC',           label: '기타' },
] as const;

// 배송비 납부 방식
export const GF_PAYMENT_METHODS = [
  { code: 'SENDER_PAY',   label: '선불 (발송인 부담)' },
  { code: 'RECEIVER_PAY', label: '착불 (수령인 부담)' },
] as const;
